Module Level

    'Level abgeschlossen einstellung
    Public level_001 As Boolean = True
    Public level_002 As Boolean = False
    Public level_003 As Boolean = False
    Public level_004 As Boolean = False
    Public level_005 As Boolean = False
    Public level_006 As Boolean = False
    Public level_007 As Boolean = False
    Public level_008 As Boolean = False
    Public level_009 As Boolean = False
    Public level_010 As Boolean = False
    Public level_011 As Boolean = False
    Public level_012 As Boolean = False
    Public level_013 As Boolean = False
    Public level_014 As Boolean = False
    Public level_015 As Boolean = False
    Public level_016 As Boolean = False
    Public level_017 As Boolean = False
    Public level_018 As Boolean = False
    Public level_019 As Boolean = False
    Public level_020 As Boolean = False
    Public level_021 As Boolean = False
    Public level_022 As Boolean = False
    Public level_023 As Boolean = False
    Public level_024 As Boolean = False
    Public level_025 As Boolean = False
    Public level_026 As Boolean = False
    Public level_027 As Boolean = False
    Public level_028 As Boolean = False
    Public level_029 As Boolean = False
    Public level_030 As Boolean = False
    Public level_031 As Boolean = False
    Public level_032 As Boolean = False
    Public level_033 As Boolean = False
    Public level_034 As Boolean = False
    Public level_035 As Boolean = False
    Public level_036 As Boolean = False
    Public level_037 As Boolean = False
    Public level_038 As Boolean = False
    Public level_039 As Boolean = False
    Public level_040 As Boolean = False
    Public level_041 As Boolean = False
    Public level_042 As Boolean = False
    Public level_043 As Boolean = False
    Public level_044 As Boolean = False
    Public level_045 As Boolean = False
    Public level_046 As Boolean = False
    Public level_047 As Boolean = False
    Public level_048 As Boolean = False
    Public level_049 As Boolean = False
    Public level_050 As Boolean = False
    Public level_051 As Boolean = False
    Public level_052 As Boolean = False
    Public level_053 As Boolean = False
    Public level_054 As Boolean = False
    Public level_055 As Boolean = False
    Public level_056 As Boolean = False
    Public level_057 As Boolean = False
    Public level_058 As Boolean = False
    Public level_059 As Boolean = False
    Public level_060 As Boolean = False
    Public level_061 As Boolean = False
    Public level_062 As Boolean = False
    Public level_063 As Boolean = False
    Public level_064 As Boolean = False
    Public level_065 As Boolean = False
    Public level_066 As Boolean = False
    Public level_067 As Boolean = False
    Public level_068 As Boolean = False
    Public level_069 As Boolean = False
    Public level_070 As Boolean = False
    Public level_071 As Boolean = False
    Public level_072 As Boolean = False

    Public Sub Level_Reset()
        Level.level_001 = True
        Level.level_002 = False
        Level.level_003 = False
        Level.level_004 = False
        Level.level_005 = False
        Level.level_006 = False
        Level.level_007 = False
        Level.level_008 = False
        Level.level_009 = False
        Level.level_010 = False
        Level.level_011 = False
        Level.level_012 = False
        Level.level_013 = False
        Level.level_014 = False
        Level.level_015 = False
        Level.level_016 = False
        Level.level_017 = False
        Level.level_018 = False
        Level.level_019 = False
        Level.level_020 = False
        Level.level_021 = False
        Level.level_022 = False
        Level.level_023 = False
        Level.level_024 = False
        Level.level_025 = False
        Level.level_026 = False
        Level.level_027 = False
        Level.level_028 = False
        Level.level_029 = False
        Level.level_030 = False
        Level.level_031 = False
        Level.level_032 = False
        Level.level_033 = False
        Level.level_034 = False
        Level.level_035 = False
        Level.level_036 = False
        Level.level_037 = False
        Level.level_038 = False
        Level.level_039 = False
        Level.level_040 = False
        Level.level_041 = False
        Level.level_042 = False
        Level.level_043 = False
        Level.level_044 = False
        Level.level_045 = False
        Level.level_046 = False
        Level.level_047 = False
        Level.level_048 = False
        Level.level_049 = False
        Level.level_050 = False
        Level.level_051 = False
        Level.level_052 = False
        Level.level_053 = False
        Level.level_054 = False
        Level.level_055 = False
        Level.level_056 = False
        Level.level_057 = False
        Level.level_058 = False
        Level.level_059 = False
        Level.level_060 = False
        Level.level_061 = False
        Level.level_062 = False
        Level.level_063 = False
        Level.level_064 = False
        Level.level_065 = False
        Level.level_066 = False
        Level.level_067 = False
        Level.level_068 = False
        Level.level_069 = False
        Level.level_070 = False
        Level.level_071 = False
        Level.level_072 = False
    End Sub


End Module